#!/bin/sh

unformatted=$(gofmt -l .)

if [ -n "$unformatted" ]; then
  echo "The following files are not formatted:"
  echo "$unformatted"
  echo "Formatting them now."
  gofmt -w .;
  exit 1
fi

go test ./...;